b.obj : error LNK2005: f は既に a.obj で定義されています。 [D:\home\khasegawa\lang\40_test_tool\vs_wrapper2\vs_wrapper2.vcxproj]
D:\home\khasegawa\lang\40_test_tool\vs_wrapper2\x64\Debug\vs_wrapper2.exe : fatal error LNK1169: 1 つ以上の複数回定義されているシンボルが見つかりました。 [D:\home\khasegawa\lang\40_test_tool\vs_wrapper2\vs_wrapper2.vcxproj]
  b.obj : error LNK2005: f は既に a.obj で定義されています。 [D:\home\khasegawa\lang\40_test_tool\vs_wrapper2\vs_wrapper2.vcxproj]
  D:\home\khasegawa\lang\40_test_tool\vs_wrapper2\x64\Debug\vs_wrapper2.exe : fatal error LNK1169: 1 つ以上の複数回定義されているシンボルが見つかりました。 [D:\home\khasegawa\lang\40_test_tool\vs_wrapper2\vs_wrapper2.vcxproj]
