include ../../../../../Makefile.ok

test002.log : test002.i
	$(DOGV) --alarm 300 $(CC1) $< $(CC1_FLAG) > $@
	$(DOS2UNIX) $@

test003.log : test003.i
	$(DOGV) --alarm 300 $(CC1) $< $(CC1_FLAG) > $@
	$(DOS2UNIX) $@
