a.obj : error LNK2019: 未解決の外部シンボル a が関数 "int __cdecl _test_main(void)" (?_test_main@@YAHXZ) で参照されました。 [D:\home\khasegawa\lang\40_test_tool\vs_wrapper2xx\vs_wrapper2xx.vcxproj]
D:\home\khasegawa\lang\40_test_tool\vs_wrapper2xx\x64\Debug\vs_wrapper2xx.exe : fatal error LNK1120: 1 件の未解決の外部参照 [D:\home\khasegawa\lang\40_test_tool\vs_wrapper2xx\vs_wrapper2xx.vcxproj]
  a.obj : error LNK2019: 未解決の外部シンボル a が関数 "int __cdecl _test_main(void)" (?_test_main@@YAHXZ) で参照されました。 [D:\home\khasegawa\lang\40_test_tool\vs_wrapper2xx\vs_wrapper2xx.vcxproj]
  D:\home\khasegawa\lang\40_test_tool\vs_wrapper2xx\x64\Debug\vs_wrapper2xx.exe : fatal error LNK1120: 1 件の未解決の外部参照 [D:\home\khasegawa\lang\40_test_tool\vs_wrapper2xx\vs_wrapper2xx.vcxproj]
