include ../../../../Makefile.ok

test000.s:test000.i
	$(DOGV) --alarm 300 $(CC1) -o $@ $< $(CC1_FLAG)

test001.s:test001.i
	$(DOGV) --alarm 300 $(CC1) -o $@ $< $(CC1_FLAG)

test002.s:test002.i
	$(DOGV) --alarm 300 $(CC1) -o $@ $< $(CC1_FLAG)

test003.s:test003.i
	$(DOGV) --alarm 300 $(CC1) -o $@ $< $(CC1_FLAG)
