include ../../../../../Makefile.ok

test000.s : test000.i
	$(DOGV) --alarm 300 $(CC1) -o $@ $< $(CC1_FLAG)

test004.s : test004.i
	$(DOGV) --alarm 300 $(CC1) -o $@ $< $(CC1_FLAG)

test005.s : test005.i
	$(DOGV) --alarm 300 $(CC1) -o $@ $< $(CC1_FLAG)
