include ../../../../../Makefile.ok

test000.s : test000.i
	$(DOGV) --alarm 300 $(CC1) $(CC1_FLAG) $<
	$(TOUCH) $@

test004.s : test004.i
	$(DOGV) --alarm 300 $(CC1) $(CC1_FLAG) $<
	$(TOUCH) $@

test005.s : test005.i
	$(DOGV) --alarm 300 $(CC1) $(CC1_FLAG) $<
	$(TOUCH) $@

CPP_FLAG_FOR_JIS = $(CPP_FLAG) -e iso2022_jp

test012.i : test012.c
	$(DOGV) $(CPP) $(CPP_FLAG_FOR_JIS) -o $p $< 
