#! /bin/csh -f

#'/Program Files/Microsoft Visual Studio/VC98/Bin/VCVARS32.BAT'

rm -r -f 1_ok
mkdir 1_ok

rm -r -f 2_error
mkdir 2_error

foreach file ( *.c )
	cl /TP $file
	if ( $status == 0 ) then
		mv $file 1_ok
	else
		mv $file 2_error
	endif
end
